[package]
name = "calcifer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.25.0"
env_logger = { version = "0.10.1", default-features = false, features = [
    "auto-color",
    "humantime",
] }
rfd = "0.12.1"
egui_extras = { version = "0.25.0" }
syntect = "4.6"
run_shell = "0.1.13"
